apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: colorgateway-vs
spec:
  provider:
    virtualRouter:
      virtualRouterRef:
        name: colorgateway-vr
---        
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: colorteller-vs
spec:
  provider:
    virtualRouter:
      virtualRouterRef:
        name: colorteller-vr