apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: colorgateway
spec:
  podSelector:
    matchLabels:
      app: colorgateway
  meshName: my-mesh
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: "colorgateway.my-apps.svc.cluster.local"

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: colorteller
spec:
  podSelector:
    matchLabels:
      app: colorteller
  meshName: my-mesh
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: "colorteller.my-apps.svc.cluster.local"
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: dnsutils
spec:
  podSelector:
    matchLabels:
      app: dnsutils
  meshName: my-mesh
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: "dnsutils.my-apps.svc.cluster.local"
